# -*- coding: utf-8 -*-
"""Contingut public de la guia d'1 pagina /guia en tots els idiomes."""

from __future__ import annotations


GUIDE: dict[str, dict[str, str]] = {
    "ca": {
        "lead": "Automatitza la gestió d’espais i horaris del teu club.",
        "sub": "S'ha acabat el malson",
        "intro": "Control total i fluid. Eleva la coordinació de pistes i horaris al següent nivell.\n\nCentralitza la gestió d'instal·lacions, entrenaments i partits de manera intel·ligent, assegurant la disponibilitat dels equips en un únic entorn sense friccions.",
        "heading": "Començar en 5 passos",
        "step1_title": "Accedeix a l'instant",
        "step1_body": "Introdueix el codi del teu club i la teva contrasenya. Sense configuracions complexes.",
        "step2_title": "Sincronització federativa automàtica",
        "step2_body": "Escriu el nom del teu club i l'aplicació importarà directament tots els partits oficials de la teva federació. Estalvia hores de feina manual.",
        "step3_title": "Defineix el teu espai",
        "step3_body": "Configura les teves pistes i les franges horàries disponibles. El sistema s'adapta a la realitat de les teves instal·lacions en un parell de clics.",
        "step4_title": "Detecció automàtica de conflictes",
        "step4_body": "AtempoSports rastreja el calendari a l'instant, t'avisa de qualsevol solapament d'horaris o persones i et serveix en safata solucions que pots aplicar amb un sol clic o modificar segons les necessitats.",
        "step5_title": "Genera, revisa i aplica",
        "step5_body": "Crea les teves sessions, valida l'esborrany i publica el resultat: blinda el teu club contra les incompatibilitats i reorganitza qualsevol canvi d'última hora de manera immediata i controlada.",
        "note": "Oblida't de la pressió, de tenir al cap cada detall, de revisar l'agenda a cada minut.",
        "footer": "Viu amb la tranquil·litat absoluta de saber que el teu calendari és lliure d'errors i totalment sota control des d'un sol lloc. AtempoSports s’encarrega de tot.",
    },
    "es": {
        "lead": "Automatiza la gestión de espacios e horarios de tu club.",
        "sub": "Se ha acabado la pesadilla.",
        "intro": "Control total y fluido. Eleva la coordinación de pistas y horarios al siguiente nivel.\n\nCentraliza la gestión de instalaciones, entrenamientos y partidos de forma inteligente, asegurando la disponibilidad de los equipos en un único entorno sin fricciones.",
        "heading": "Empezar en 5 pasos",
        "step1_title": "Accede al instante",
        "step1_body": "Introduce el código de tu club y tu contraseña. Sin configuraciones complejas.",
        "step2_title": "Sincronización federativa automática",
        "step2_body": "Escribe el nombre de tu club y la aplicación importará directamente todos los partidos oficiales de tu federación. Ahorra horas de trabajo manual.",
        "step3_title": "Define tu espacio",
        "step3_body": "Configura tus pistas y las franjas horarias disponibles. El sistema se adapta a la realidad de tus instalaciones en un par de clics.",
        "step4_title": "Detección automática de conflictos",
        "step4_body": "AtempoSports revisa el calendario por ti. Detecta cualquier solapamiento de horarios o de personas y te propone alternativas inteligentes que puedes aceptar o modificar a tu gusto.",
        "step5_title": "Genera, revisa y aplica",
        "step5_body": "Crea los entrenamientos, revisa el borrador general y publica los cambios. Ahorra tiempo, evita dobles reservas y reprograma partidos fácilmente ante cualquier cambio de última hora.",
        "note": "Deja de luchar con hojas de cálculo infinitas. AtempoSports lo hace por ti.",
        "footer": "Mantén el control total del calendario oficial, sin errores humanos y desde un solo lugar.",
    },
    "eu": {
        "lead": "Automatizatu zure klubaren espazio eta ordutegien kudeaketa.",
        "sub": "Amets gaiztoak amaitu dira.",
        "intro": "Kontrol osoa eta islatua. Zure pista eta ordutegien koordinazioa hurrengo mailara igo.\n\nInstalazioen, entrenamenduen eta partiduen kudeaketa adimentsen zentralizatu, taldeen eskuragarritasuna bermatu eta marruskadurarik gabeko ingurune bakar batean.",
        "heading": "Hasi 5 urratsetan",
        "step1_title": "Sarbide berehalakoa",
        "step1_body": "Sartu zure klubaren kodea eta pasahitza. Konfigurazio konplexurik gabe.",
        "step2_title": "Federazioko sinkronizazio automatikoa",
        "step2_body": "Idatzi zure klubaren izena eta aplikazioak zure federazioko partidu ofizial guztiak inportatuko ditu zuzenean. Aurreztu eskuzko lan orduak.",
        "step3_title": "Definitu zure espazioa",
        "step3_body": "Konfiguratu zure pistak eta eskuragarri dauden ordutegi-tarteak. Sistema klik pare batean egokituta dago zure instalazioetara.",
        "step4_title": "Gatazka detekzio automatikoa",
        "step4_body": "AtempoSports-k egutegia zuretzat berrikusten du. Ordutegi edo pertsonen gainjartzeak detektatzen ditu eta onartu edo nahi duzun bezala alda ditzakezun aukera adimentsuak proposatzen dizkizu.",
        "step5_title": "Sortu, berrikusi eta aplikatu",
        "step5_body": "Sortu entrenamenduak, berrikusi zirriborro orokorra eta argitaratu aldaketak. Aurreztu denbora, saihestu erreserba bikoitzak eta mugitu partiduak erraz azken uneko aldaketei aurre egiteko.",
        "note": "Ez jarraitu kalkulu-orri amaigabeekin borrokan. AtempoSports-k egiten du zuretzat.",
        "footer": "Mantendu egutegi ofizialaren kontrol osoa, errore gizakorrik gabe eta leku bakar batetik.",
    },
    "gl": {
        "lead": "Automatiza a xestión de espazos e horarios do teu club.",
        "sub": "Acabouse a pesadelo.",
        "intro": "Control total e fluído. Eleva a coordinación de pistas e horarios ao seguinte nivel.\n\nCentraliza a xestión de instalacións, adestramentos e partidos de xeito intelixente, asegurando a dispoñibilidade dos equipos nun único entorno sen friccións.",
        "heading": "Comezar en 5 pasos",
        "step1_title": "Accede nun instante",
        "step1_body": "Introduce o código do teu club e o teu contrasinal. Sen configuracións complexas.",
        "step2_title": "Sincronización federativa automática",
        "step2_body": "Escribe o nome do teu club e a aplicación importará directamente todos os partidos oficiais da túa federación. Aforra horas de traballo manual.",
        "step3_title": "Define o teu espazo",
        "step3_body": "Configura as túas pistas e as franxas horarias dispoñibles. O sistema adáptase á realidade das túas instalacións nun par de clics.",
        "step4_title": "Detección automática de conflitos",
        "step4_body": "AtempoSports revisa o calendario por ti. Detecta calquera solapamento de horarios ou de persoas e proponseche alternativas intelixentes que podes aceptar ou modificar ao teu criterio.",
        "step5_title": "Xera, revisa e aplica",
        "step5_body": "Crea adestramentos, revisa o borrador xeral e publica os cambios. Aforra tempo, evita dobres reservas e reprograma partidos facilmente ante calquera cambio de última hora.",
        "note": "Deixa de loitar con follas de cálculo infinitas. AtempoSports faecho por ti.",
        "footer": "Mantén o control total do calendario oficial, sen erros humanos e desde un só lugar.",
    },
    "fr": {
        "lead": "Automatisez la gestion des espaces et des horaires de votre club.",
        "sub": "Cauchemar terminé.",
        "intro": "Contrôle total et fluide. Élevez la coordination des pistes et des horaires au niveau supérieur.\n\nCentralisez la gestion des installations, des entraînements et des matchs de manière intelligente, en assurant la disponibilité des équipes dans un environnement unique sans friction.",
        "heading": "Commencer en 5 étapes",
        "step1_title": "Accès instantané",
        "step1_body": "Saisissez le code du club et le mot de passe. Aucune configuration complexe.",
        "step2_title": "Synchronisation fédérale automatique",
        "step2_body": "Entrez le nom du club et l'application importera directement tous les matchs officiels de votre fédération. Gagnez des heures de travail manuel.",
        "step3_title": "Définissez votre espace",
        "step3_body": "Configurez les pistes et les créneaux disponibles. Le système s'adapte à vos installations en quelques clics.",
        "step4_title": "Détection automatique des conflits",
        "step4_body": "AtempoSports vérifie le calendrier pour vous. Il détecte toute superposition d'horaires ou de personnes et vous propose des alternatives intelligentes à accepter ou à modifier à votre guise.",
        "step5_title": "Générez, révisez et appliquez",
        "step5_body": "Créez les entraînements, révisez le brouillon global et publiez les changements. Gagnez du temps, évitez les doubles réservations et reprogrammez les matchs facilement en cas de changement de dernière minute.",
        "note": "Arrêtez de lutter contre des tableurs interminables. AtempoSports le fait pour vous.",
        "footer": "Gardez le contrôle total du calendrier officiel, sans erreur humaine et depuis un seul endroit.",
    },
    "it": {
        "lead": "Automatizza la gestione di spazi e orari del tuo club.",
        "sub": "Il brutto sogno è finito.",
        "intro": "Controllo totale e fluido. Porta la coordinazione di campi e orari al livello successivo.\n\nCentralizza la gestione di impianti, allenamenti e partite in modo intelligente, assicurando la disponibilità delle squadre in un unico ambiente senza attriti.",
        "heading": "Inizia in 5 passaggi",
        "step1_title": "Accesso istantaneo",
        "step1_body": "Inserisci il codice del club e la password. Nessuna configurazione complessa.",
        "step2_title": "Sincronizzazione federale automatica",
        "step2_body": "Scrivi il nome del club e l'applicazione importerà direttamente tutte le partite ufficiali della tua federazione. Risparmia ore di lavoro manuale.",
        "step3_title": "Definisci il tuo spazio",
        "step3_body": "Configura le piste e le fasce orarie disponibili. Il sistema si adatta alla realtà delle tue strutture in un paio di clic.",
        "step4_title": "Rilevamento automatico dei conflitti",
        "step4_body": "AtempoSports controlla il calendario per te. Rileva ogni sovrapposizione di orari o persone e ti propone alternative intelligenti da accettare o modificare a piacere.",
        "step5_title": "Genera, rivedi e applica",
        "step5_body": "Crea allenamenti, rivedi la bozza generale e pubblica le modifiche. Risparmia tempo, evita doppie prenotazioni e riprogramma partite facilmente di fronte a qualsiasi cambio dell'ultimo minuto.",
        "note": "Smetti di lottare con fogli di calcolo infiniti. AtempoSports lo fa per te.",
        "footer": "Mantieni il controllo totale del calendario ufficiale, senza errori umani e da un solo posto.",
    },
    "pt": {
        "lead": "Automatiza a gestão de espaços e horários do teu clube.",
        "sub": "O pesadelo acabou.",
        "intro": "Controlo total e fluido. Eleve a coordenação de pistas e horários ao próximo nível.\n\nCentralize a gestão de instalações, treinos e jogos de forma inteligente, assegurando a disponibilidade das equipas num único ambiente sem fricções.",
        "heading": "Começar em 5 passos",
        "step1_title": "Acede num instante",
        "step1_body": "Introduz o código do teu clube e a tua palavra-passe. Sem configurações complexas.",
        "step2_title": "Sincronização federativa automática",
        "step2_body": "Escreve o nome do teu clube e a aplicação importará diretamente todos os jogos oficiais da tua federação. Poupa horas de trabalho manual.",
        "step3_title": "Define o teu espaço",
        "step3_body": "Configura as tuas pistas e as franjas horárias disponíveis. O sistema adapta-se à realidade das tuas instalações em uns cliques.",
        "step4_title": "Deteção automática de conflitos",
        "step4_body": "O AtempoSports revê o calendário por ti. Deteta qualquer sobreposição de horários ou pessoas e propõe alternativas inteligentes que podes aceitar ou modificar ao teu gosto.",
        "step5_title": "Gera, revisa e aplica",
        "step5_body": "Cria treinos, revisa o rascunho geral e publica as alterações. Poupa tempo, evita duplas reservas e reprograma jogos facilmente perante qualquer mudança de última hora.",
        "note": "Deixa de lutar com folhas de cálculo infinitas. O AtempoSports faz isso por ti.",
        "footer": "Mantém o controlo total do calendário oficial, sem erros humanos e a partir de um só lugar.",
    },
    "de": {
        "lead": "Automatisieren Sie die Raum- und Zeitplanung Ihres Vereins.",
        "sub": "Der Albtraum ist vorbei.",
        "intro": "Totale und flüssige Kontrolle. Heben Sie die Koordination von Plätzen und Zeiten auf die nächste Ebene.\n\nZentralisieren Sie die Verwaltung von Anlagen, Trainingseinheiten und Spielen intelligent und stellen Sie die Verfügbarkeit der Mannschaften in einer einzigen reibungslosen Umgebung sicher.",
        "heading": "In 5 Schritten loslegen",
        "step1_title": "Sofortiger Zugang",
        "step1_body": "Geben Sie den Vereinscode und das Passwort ein. Keine komplexe Einrichtung.",
        "step2_title": "Automatische Verbandssynchronisierung",
        "step2_body": "Geben Sie den Vereinsnamen ein und die App importiert direkt alle Pflichtspiele Ihres Verbands. Sparen Sie Stunden manueller Arbeit.",
        "step3_title": "Definieren Sie Ihren Raum",
        "step3_body": "Richten Sie Ihre Plätze und verfügbaren Zeitfenster ein. Das System passt sich in wenigen Klicks an die Realität Ihrer Anlagen an.",
        "step4_title": "Automatische Konflikterkennung",
        "step4_body": "AtempoSports prüft den Kalender für Sie. Es erkennt jede Termin- oder Personenüberschneidung und schlägt Ihnen intelligente Alternativen vor, die Sie annehmen oder nach Belieben anpassen können.",
        "step5_title": "Generieren, prüfen und übernehmen",
        "step5_body": "Erstellen Sie Trainingseinheiten, prüfen Sie den Gesamtentwurf und veröffentlichen Sie Änderungen. Sparen Sie Zeit, vermeiden Sie Doppelbelegungen und verschieben Sie Spiele bei kurzfristigen Änderungen.",
        "note": "Schluss mit endlosen Tabellenkalkulationen. AtempoSports erledigt es für Sie.",
        "footer": "Behalten Sie die volle Kontrolle über den offiziellen Spielplan, ohne menschliche Fehler und an einem einzigen Ort.",
    },
    "en": {
        "lead": "Automate your club’s space and schedule management.",
        "sub": "The nightmare is over.",
        "intro": "Total and fluid control. Take your pitch and schedule coordination to the next level.\n\nCentralise the management of facilities, trainings and matches intelligently, ensuring team availability in a single frictionless environment.",
        "heading": "Get started in 5 steps",
        "step1_title": "Instant access",
        "step1_body": "Enter your club code and password. No complex setup.",
        "step2_title": "Automatic federation sync",
        "step2_body": "Type your club name and the app will import all official matches from your federation directly. Save hours of manual work.",
        "step3_title": "Define your space",
        "step3_body": "Set up your venues and available time slots. The system adapts to your facilities in a couple of clicks.",
        "step4_title": "Automatic conflict detection",
        "step4_body": "AtempoSports checks the calendar for you. It detects any schedule or people overlap and suggests smart alternatives you can accept or tweak.",
        "step5_title": "Generate, review and apply",
        "step5_body": "Create trainings, review the overall draft and publish changes. Save time, avoid double bookings and reschedule matches easily when anything last-minute changes.",
        "note": "Stop fighting endless spreadsheets. AtempoSports does it for you.",
        "footer": "Keep full control of the official calendar, without human errors and from a single place.",
    },
}


def get_guide(lang: str) -> dict[str, str]:
    """Retorna la guia en l'idioma demanat, o en català si encara no existeix."""
    return GUIDE.get(lang, GUIDE["ca"])
