# -*- coding: utf-8 -*-
"""Contingut public de la landing page / en tots els idiomes."""

from __future__ import annotations


LANDING: dict[str, dict[str, str]] = {
    "ca": {
        "tagline": "Organitza't sense embolics",
        "hook": "El cap de setmana d'un club és el resultat d'innumerables hores intentant quadrar el cercle amb missatges, Excels i papers. I sovint el que hauria de ser senzill — saber qui juga, on i a quina hora — es converteix en un caos. AtempoSports neix perquè el coordinador, l'entrenador i el club tornin a tenir el control.",
        "promise": "Un únic calendari. Tot sota control.",
        "promise_text": "Centralitza entrenaments, partits, pistes i equips en un sol lloc. Tu decideixes; l'app t'organitza.",
        "features_title": "Com t'ajuda, pas a pas?",
        "feature_1": "Connecta la federació",
        "feature_1_text": "Importa els calendaris oficials d'hoquei patins i s'adapta als canvis que facin. Tu ja no copies a mà.",
        "feature_2": "Defineix el teu espai",
        "feature_2_text": "Afegeix les teves pistes, franges horàries i indisponibilitats.",
        "feature_3": "Organitza equips i jugadors",
        "feature_3_text": "Tota la plantilla al seu lloc.",
        "feature_4": "Genera plans ràpid",
        "feature_4_text": "Crea entrenaments i ajusta'ls manualment, com fas ara, però en minuts en lloc d'hores.",
        "feature_5": "Detecta i proposa solucions",
        "feature_5_text": "L'app t'alerta de solapaments d'horaris, espais o persones i et proposa ajustos. Sempre els pots modificar manualment.",
        "feature_6": "Publica amb seguretat",
        "feature_6_text": "Quan tu ho aproves, el calendari queda llest per a tothom.",
        "communicate_title": "Comunica els canvis",
        "communicate_text": "Si un ajust requereix parlar-ho amb un equip o un grup, AtempoSports et genera el missatge de WhatsApp ja redactat, perquè puguis consultar i decidir amb tothom.",
        "human_title": "Fet per coordinadors, no per robots",
        "human_text": "Cada decisió passa per tu. AtempoSports només et treu la feina bruta: recopilar dades, trobar errors, proposar opcions i redactar el que cal compartir. Tu confirmes, tu aproves.",
        "beta_title": "Beta exclusiva per a clubs fundadors",
        "beta_text": "De moment, l'accés és per invitació. Aviat obrim el registre: 12 setmanes d'accés total gratuït, sense compromís ni targeta. El teu club podrà provar AtempoSports abans que obrim els plans de pagament.",
        "multi_title": "Multiesport",
        "multi_text": "Ara l'sync federativa és automàtica per a hoquei patins. Pots gestionar manualment futbol, futbol sala, bàsquet, handbol i altres esports al mateix espai; la connexió automàtica amb les seves federacions arribarà properament.",
        "login_btn": "Entrar",
        "signup_btn": "Crear compte — Pròximament",
    },
    "es": {
        "tagline": "Organízate sin líos",
        "hook": "El fin de semana de un club es el resultado de innumerables horas intentando cuadrar el círculo con mensajes, Excels y papeles. Y a menudo lo que debería ser sencillo — saber quién juega, dónde y a qué hora — se convierte en un caos. AtempoSports nace para que el coordinador, el entrenador y el club vuelvan a tener el control.",
        "promise": "Un único calendario. Todo bajo control.",
        "promise_text": "Centraliza entrenamientos, partidos, pistas y equipos en un solo lugar. Tú decides; la app te organiza.",
        "features_title": "¿Cómo te ayuda, paso a paso?",
        "feature_1": "Conecta la federación",
        "feature_1_text": "Importa los calendarios oficiales de hockey patines y se adapta a los cambios que hagan. Tú ya no copias a mano.",
        "feature_2": "Define tu espacio",
        "feature_2_text": "Añade tus pistas, franjas horarias e indisponibilidades.",
        "feature_3": "Organiza equipos y jugadores",
        "feature_3_text": "Toda la plantilla en su sitio.",
        "feature_4": "Genera planes rápido",
        "feature_4_text": "Crea entrenamientos y ajústalos manualmente, como haces ahora, pero en minutos en lugar de horas.",
        "feature_5": "Detecta y propone soluciones",
        "feature_5_text": "La app te alerta de solapamientos de horarios, espacios o personas y te propone ajustes. Siempre puedes modificarlos manualmente.",
        "feature_6": "Publica con seguridad",
        "feature_6_text": "Cuando tú lo apruebas, el calendario queda listo para todos.",
        "communicate_title": "Comunica los cambios",
        "communicate_text": "Si un ajuste requiere hablarlo con un equipo o un grupo, AtempoSports te genera el mensaje de WhatsApp ya redactado, para que puedas consultar y decidir con todos.",
        "human_title": "Hecho para coordinadores, no para robots",
        "human_text": "Cada decisión pasa por ti. AtempoSports solo te quita el trabajo bruto: recopilar datos, encontrar errores, proponer opciones y redactar lo que hay que compartir. Tú confirmas, tú apruebas.",
        "beta_title": "Beta exclusiva para clubs fundadores",
        "beta_text": "De momento, el acceso es por invitación. Pronto abrimos el registro: 12 semanas de acceso total gratuito, sin compromiso ni tarjeta. Tu club podrá probar AtempoSports antes de que abramos los planes de pago.",
        "multi_title": "Multideporte",
        "multi_text": "Ahora la sincronización federativa es automática para hockey patines. Puedes gestionar manualmente fútbol, fútbol sala, baloncesto, balonmano y otros deportes en el mismo espacio; la conexión automática con sus federaciones llegará próximamente.",
        "login_btn": "Entrar",
        "signup_btn": "Crear cuenta — Próximamente",
    },
    "eu": {
        "tagline": "Kirol antolakuntza, nahasmenik gabe",
        "hook": "Klub bateko asteburuak orduetan erabakitzen dira. Eta sarritan, sinplea izan beharko litzatekeena — nor jokatzen duen, non eta zein ordutan — mezu, Excel eta paperen puzle bihurtzen da. AtempoSports koordinatzaileak, entrenatzaileak eta klubak berriro kontrola izan dezaten jaio da.",
        "promise": "Egutegi bakarra. Dena kontrolpean.",
        "promise_text": "Entrenamenduak, partiduak, pistak eta taldeak leku bakarrean biltzen ditu. Zuk erabakitzen duzu; app-ak antolatzen zaitu.",
        "features_title": "Nola laguntzen dizu, pausoz pauso?",
        "feature_1": "Federazioarekin konektatu",
        "feature_1_text": "Hockey patineko egutegi ofizialak inportatzen ditu eta federazioak egiten dituen aldaketetara egokitzen da. Zuk ez duzu eskuz kopiatu behar.",
        "feature_2": "Zure espazioa zehaztu",
        "feature_2_text": "Gehitu zure pistak, ordutegi-tarteak eta ez-eskuragarritasunak.",
        "feature_3": "Taldeak eta jokalariak antolatu",
        "feature_3_text": "Plantila osoa bere lekuan.",
        "feature_4": "Planak azkar sortu",
        "feature_4_text": "Sortu entrenamenduak eta eskuz doitu, orain egiten duzun bezala, baina orduetan egon beharrean minutuetan.",
        "feature_5": "Detektatu eta irtenbideak proposatu",
        "feature_5_text": "App-ak ordutegi, espazio edo pertsonen gainjartzeak ohartarazten dizkizu eta doikuntzak proposatzen dizkizu. Beti eskuz alda ditzakezu.",
        "feature_6": "Argitaratu segurtasunez",
        "feature_6_text": "Zuk onartzen duzunean, egutegia denentzat prest dago.",
        "communicate_title": "Komunikatu aldaketak",
        "communicate_text": "Doikuntza batek talde edo talde batekin hitz egitea eskatzen badu, AtempoSports WhatsApp mezua idatzita sortzen dizu, guztiekin kontsultatu eta erabaki ahal dezazun.",
        "human_title": "Koordinatzaileentzat egina, robotentzat ez",
        "human_text": "Erabaki bakoitza zugatik pasatzen da. AtempoSports-ek lan zikina baino ez du kentzen: datuak biltzea, erroreak aurkitzea, aukerak proposatzea eta partekatu behar dena idaztea. Zuk baieztatzen duzu, zuk onartzen duzu.",
        "beta_title": "Beta esklusiboa sortzaile klubentzat",
        "beta_text": "Batu orain eta gozatu 12 aste sarbide guztiz dohainik, konpromisorik edo txartelik gabe. Zure klubak AtempoSports probatu ahal izango du ordain-planak ireki baino lehen.",
        "multi_title": "Kirol anitza",
        "multi_text": "Orain federazioko sinkronizazioa hockey patinerako automatikoa da. Futbola, futbol sala, saskibaloa, eskubaloia eta beste kirol batzuk eskuz kudea ditzakezu leku berean; haien federazioekin konexio automatikoa laster iritsiko da.",
        "login_btn": "Sartu",
        "signup_btn": "Kontua sortu — Laster",
    },
    "gl": {
        "tagline": "Organización deportiva, sen caos",
        "hook": "O fin de semana dun club decídese en horas. E moitas veces o que debería ser sinxelo — saber quen xoga, onde e a que hora — convértese nun puzle de mensaxes, Excels e papeis. AtempoSports nace para que o coordinador, o adestrador e o club volvan ter o control.",
        "promise": "Un único calendario. Todo baixo control.",
        "promise_text": "Centraliza adestramentos, partidos, pistas e equipos nun só lugar. Ti decides; a app organizate.",
        "features_title": "Como che axuda, paso a paso?",
        "feature_1": "Conecta a federación",
        "feature_1_text": "Importa os calendarios oficiais de hóckey a patíns e adaptase aos cambios que fagan. Ti non copias a man.",
        "feature_2": "Define o teu espazo",
        "feature_2_text": "Engade as túas pistas, franxas horarias e indisponibilidades.",
        "feature_3": "Organiza equipos e xogadores",
        "feature_3_text": "Toda a plantilla no seu lugar.",
        "feature_4": "Xera plans rápido",
        "feature_4_text": "Crea adestramentos e axústaos manualmente, como fas agora, pero en minutos no lugar de horas.",
        "feature_5": "Detecta e propón solucións",
        "feature_5_text": "A app alertate de solapamentos de horarios, espazos ou persoas e proponseche axustes. Sempre os podes modificar manualmente.",
        "feature_6": "Publica con seguridade",
        "feature_6_text": "Cando ti o aprobas, o calendario queda listo para todos.",
        "communicate_title": "Comunica os cambios",
        "communicate_text": "Se un axuste require falarlo cun equipo ou grupo, AtempoSports xeraseche a mensaxe de WhatsApp xa redactada, para que poidas consultar e decidir con todos.",
        "human_title": "Feito para coordinadores, non para robots",
        "human_text": "Cada decisión pasa por ti. AtempoSports só che quita o traballo bruto: recopilar datos, atopar erros, propoñer opcións e redactar o que hai que compartir. Ti confirmas, ti aprobas.",
        "beta_title": "Beta exclusiva para clubs fundadores",
        "beta_text": "Únete agora e goza de 12 semanas de acceso total de balde, sen compromiso nin tarxeta. O teu club poderá probar AtempoSports antes de que abramos os plans de pago.",
        "multi_title": "Multideporte",
        "multi_text": "Agora a sincronización federativa é automática para hóckey a patíns. Podes xestionar manualmente fútbol, fútbol sala, baloncesto, balonmán e outros deportes no mesmo espazo; a conexión automática coas súas federacións chegará proximamente.",
        "login_btn": "Acceder",
        "signup_btn": "Crear conta — Próximamente",
    },
    "fr": {
        "tagline": "Organisation sportive, sans chaos",
        "hook": "Le week-end d'un club se décide en heures. Et souvent, ce qui devrait être simple — savoir qui joue, où et à quelle heure — devient un puzzle de messages, Excel et papiers. AtempoSports est né pour que le coordinateur, l'entraîneur et le club reprennent le contrôle.",
        "promise": "Un seul calendrier. Tout sous contrôle.",
        "promise_text": "Centralisez entraînements, matchs, pistes et équipes en un seul endroit. Vous décidez ; l'application vous organise.",
        "features_title": "Comment ça vous aide, étape par étape ?",
        "feature_1": "Connectez la fédération",
        "feature_1_text": "Importez les calendriers officiels de hockey à roulettes et adaptez-vous aux changements. Vous ne copiez plus à la main.",
        "feature_2": "Définissez votre espace",
        "feature_2_text": "Ajoutez vos pistes, créneaux horaires et indisponibilités.",
        "feature_3": "Organisez équipes et joueurs",
        "feature_3_text": "Toute l'effectif à sa place.",
        "feature_4": "Générez des plans rapidement",
        "feature_4_text": "Créez des entraînements et ajustez-les manuellement, comme maintenant, mais en minutes au lieu d'heures.",
        "feature_5": "Détectez et proposez des solutions",
        "feature_5_text": "L'application vous alerte des chevauchements d'horaires, d'espaces ou de personnes et propose des ajustements. Vous pouvez toujours les modifier manuellement.",
        "feature_6": "Publiez en toute sécurité",
        "feature_6_text": "Quand vous approuvez, le calendrier est prêt pour tout le monde.",
        "communicate_title": "Communiquez les changements",
        "communicate_text": "Si un ajustement nécessite d'en parler avec une équipe ou un groupe, AtempoSports génère le message WhatsApp déjà rédigé, pour que vous puissiez consulter et décider avec tout le monde.",
        "human_title": "Fait pour les coordinateurs, pas pour les robots",
        "human_text": "Chaque décision passe par vous. AtempoSports ne vous enlève que le travail pénible : rassembler les données, trouver les erreurs, proposer des options et rédiger ce qu'il faut partager. Vous confirmez, vous approuvez.",
        "beta_title": "Bêta exclusive pour clubs fondateurs",
        "beta_text": "Rejoignez maintenant et profitez de 12 semaines d'accès totalement gratuit, sans engagement ni carte. Votre club pourra tester AtempoSports avant l'ouverture des plans de paiement.",
        "multi_title": "Multisport",
        "multi_text": "Actuellement, la synchronisation fédérale est automatique pour le hockey à roulettes. Vous pouvez gérer manuellement football, futsal, basket, handball et d'autres sports dans le même espace ; la connexion automatique avec leurs fédérations arrivera prochainement.",
        "login_btn": "Entrer",
        "signup_btn": "Créer un compte — Bientôt",
    },
    "it": {
        "tagline": "Organizzazione sportiva, senza caos",
        "hook": "Il weekend di un club si decide in poche ore. E spesso quello che dovrebbe essere semplice — sapere chi gioca, dove e a che ora — diventa un puzzle di messaggi, Excel e fogli. AtempoSports nasce perché il coordinatore, l'allenatore e il club tornino ad avere il controllo.",
        "promise": "Un unico calendario. Tutto sotto controllo.",
        "promise_text": "Centralizza allenamenti, partite, campi e squadre in un unico posto. Tu decidi; l'app ti organizza.",
        "features_title": "Come ti aiuta, passo dopo passo?",
        "feature_1": "Connetti la federazione",
        "feature_1_text": "Importa i calendari ufficiali di hockey su rotelle e si adatta ai cambiamenti. Tu non copi più a mano.",
        "feature_2": "Definisci il tuo spazio",
        "feature_2_text": "Aggiungi i tuoi campi, fasce orarie e indisponibilità.",
        "feature_3": "Organizza squadre e giocatori",
        "feature_3_text": "Tutta la rosa al suo posto.",
        "feature_4": "Genera piani velocemente",
        "feature_4_text": "Crea allenamenti e aggiustali manualmente, come fai ora, ma in minuti invece che in ore.",
        "feature_5": "Rileva e proponi soluzioni",
        "feature_5_text": "L'app ti avvisa di sovrapposizioni di orari, spazi o persone e ti propone aggiustamenti. Puoi sempre modificarli manualmente.",
        "feature_6": "Pubblica con sicurezza",
        "feature_6_text": "Quando tu approvi, il calendario è pronto per tutti.",
        "communicate_title": "Comunica i cambiamenti",
        "communicate_text": "Se una modifica richiede di parlarne con una squadra o un gruppo, AtempoSports genera il messaggio WhatsApp già scritto, così puoi consultare e decidere con tutti.",
        "human_title": "Fatto per coordinatori, non per robot",
        "human_text": "Ogni decisione passa da te. AtempoSports toglie solo il lavoro pesante: raccogliere dati, trovare errori, proporre opzioni e redigere ciò che va condiviso. Tu confermi, tu approvi.",
        "beta_title": "Beta esclusiva per club fondatori",
        "beta_text": "Unisciti ora e goditi 12 settimane di accesso totalmente gratuito, senza impegno né carta. Il tuo club potrà provare AtempoSports prima che apriamo i piani a pagamento.",
        "multi_title": "Multisport",
        "multi_text": "Attualmente la sincronizzazione federale è automatica per l'hockey su rotelle. Puoi gestire manualmente calcio, calcio a 5, basket, pallamano e altri sport nello stesso spazio; la connessione automatica con le loro federazioni arriverà prossimamente.",
        "login_btn": "Accedi",
        "signup_btn": "Crea account — Prossimamente",
    },
    "pt": {
        "tagline": "Organização desportiva, sem caos",
        "hook": "O fim de semana de um clube decide-se em horas. E muitas vezes o que deveria ser simples — saber quem joga, onde e a que horas — torna-se um puzzle de mensagens, Excels e papéis. A AtempoSports nasceu para que o coordenador, o treinador e o clube voltem a ter o controlo.",
        "promise": "Um único calendário. Tudo sob controlo.",
        "promise_text": "Centraliza treinos, jogos, pistas e equipas num só lugar. Tu decides; a app organiza-te.",
        "features_title": "Como te ajuda, passo a passo?",
        "feature_1": "Conecta a federação",
        "feature_1_text": "Importa os calendários oficiais de hóquei em patins e adapta-se às alterações. Tu já não copias à mão.",
        "feature_2": "Define o teu espaço",
        "feature_2_text": "Adiciona as tuas pistas, franjas horárias e indisponibilidades.",
        "feature_3": "Organiza equipas e jogadores",
        "feature_3_text": "Toda a plantel no seu lugar.",
        "feature_4": "Gera planos rápido",
        "feature_4_text": "Cria treinos e ajusta-os manualmente, como fazes agora, mas em minutos em vez de horas.",
        "feature_5": "Deteta e propõe soluções",
        "feature_5_text": "A app alerta-te de sobreposições de horários, espaços ou pessoas e propõe ajustes. Podes sempre modificá-los manualmente.",
        "feature_6": "Publica com segurança",
        "feature_6_text": "Quando tu aprovas, o calendário fica pronto para todos.",
        "communicate_title": "Comunica as alterações",
        "communicate_text": "Se um ajuste requer falar com uma equipa ou grupo, a AtempoSports gera a mensagem de WhatsApp já redigida, para que possas consultar e decidir com todos.",
        "human_title": "Feito para coordenadores, não para robôs",
        "human_text": "Cada decisão passa por ti. A AtempoSports só te tira o trabalho pesado: recolher dados, encontrar erros, propor opções e redigir o que é preciso partilhar. Tu confirmas, tu aprovas.",
        "beta_title": "Beta exclusiva para clubs fundadores",
        "beta_text": "Junta-te agora e desfruta de 12 semanas de acesso totalmente grátis, sem compromisso nem cartão. O teu clube poderá experimentar a AtempoSports antes de abrirmos os planos de pagamento.",
        "multi_title": "Multidesporto",
        "multi_text": "Atualmente, a sincronização federativa é automática para hóquei em patins. Podes gerir manualmente futebol, futsal, basquetebol, andebol e outros desportos no mesmo espaço; a ligação automática com as respetivas federações chegará em breve.",
        "login_btn": "Entrar",
        "signup_btn": "Criar conta — Brevemente",
    },
    "en": {
        "tagline": "Sports organisation, without the mess",
        "hook": "A club's weekend is decided in hours. And often what should be simple — knowing who plays, where and when — turns into a puzzle of messages, Excels and papers. AtempoSports exists so the coordinator, the coach and the club can be in control again.",
        "promise": "One calendar. Everything under control.",
        "promise_text": "Centralise trainings, matches, pitches and teams in one place. You decide; the app organises you.",
        "features_title": "How it helps you, step by step",
        "feature_1": "Connect the federation",
        "feature_1_text": "Imports the official rink hockey calendars and adapts to federation changes. You no longer copy by hand.",
        "feature_2": "Define your space",
        "feature_2_text": "Add your pitches, time slots and unavailability.",
        "feature_3": "Organise teams and players",
        "feature_3_text": "The whole squad in its place.",
        "feature_4": "Generate plans quickly",
        "feature_4_text": "Create trainings and adjust them manually, as you do now, but in minutes instead of hours.",
        "feature_5": "Detect and propose solutions",
        "feature_5_text": "The app alerts you to schedule, space or people overlaps and proposes adjustments. You can always modify them manually.",
        "feature_6": "Publish with confidence",
        "feature_6_text": "When you approve, the calendar is ready for everyone.",
        "communicate_title": "Communicate changes",
        "communicate_text": "If an adjustment needs discussing with a team or group, AtempoSports generates the WhatsApp message already written, so you can consult and decide with everyone.",
        "human_title": "Built for coordinators, not robots",
        "human_text": "Every decision goes through you. AtempoSports only removes the grunt work: gathering data, finding errors, proposing options and drafting what needs sharing. You confirm, you approve.",
        "beta_title": "Exclusive beta for founding clubs",
        "beta_text": "Join now and enjoy 12 weeks of completely free access, with no commitment or card. Your club can try AtempoSports before we open paid plans.",
        "multi_title": "Multisport",
        "multi_text": "Federation sync is currently automatic for rink hockey. You can manually manage football, futsal, basketball, handball and other sports in the same space; automatic connection with their federations will come soon.",
        "login_btn": "Log in",
        "signup_btn": "Create account — Coming soon",
    },
    "de": {
        "tagline": "Sportliche Organisation, ohne Chaos",
        "hook": "Das Wochenende eines Vereins entscheidet sich in Stunden. Und oft wird das, was einfach sein sollte — wer spielt, wo und wann — ein Puzzle aus Nachrichten, Excel-Tabellen und Papieren. AtempoSports wurde geschaffen, damit der Koordinator, der Trainer und der Verein wieder die Kontrolle haben.",
        "promise": "Ein einziger Kalender. Alles unter Kontrolle.",
        "promise_text": "Zentralisiere Training, Spiele, Plätze und Mannschaften an einem Ort. Du entscheidest; die App organisiert dich.",
        "features_title": "Wie es dir hilft, Schritt für Schritt",
        "feature_1": "Verbinde den Verband",
        "feature_1_text": "Importiert die offiziellen Rollhockey-Kalender und passt sich an Verbandsänderungen an. Du kopierst nicht mehr per Hand.",
        "feature_2": "Definiere deinen Raum",
        "feature_2_text": "Füge deine Plätze, Zeitfenster und Nichterreichbarkeiten hinzu.",
        "feature_3": "Organisiere Mannschaften und Spieler",
        "feature_3_text": "Der ganze Kader an seinem Platz.",
        "feature_4": "Erstelle Pläne schnell",
        "feature_4_text": "Erstelle Trainingseinheiten und passe sie manuell an, wie du es jetzt tust, aber in Minuten statt in Stunden.",
        "feature_5": "Erkenne und schlage Lösungen vor",
        "feature_5_text": "Die App warnt dich vor Überschneidungen von Zeiten, Räumen oder Personen und schlägt Anpassungen vor. Du kannst sie jederzeit manuell ändern.",
        "feature_6": "Veröffentliche mit Sicherheit",
        "feature_6_text": "Wenn du es freigibst, ist der Kalender für alle bereit.",
        "communicate_title": "Änderungen kommunizieren",
        "communicate_text": "Wenn eine Anpassung ein Gespräch mit einer Mannschaft oder Gruppe erfordert, generiert AtempoSports die WhatsApp-Nachricht bereits formuliert, damit du mit allen beraten und entscheiden kannst.",
        "human_title": "Gemacht für Koordinatoren, nicht für Roboter",
        "human_text": "Jede Entscheidung läuft über dich. AtempoSports nimmt dir nur die schwere Arbeit ab: Daten sammeln, Fehler finden, Optionen vorschlagen und das zu verfassen, was geteilt werden muss. Du bestätigst, du genehmigst.",
        "beta_title": "Exklusive Beta für Gründungsvereine",
        "beta_text": "Mach jetzt mit und genieße 12 Wochen komplett kostenlosen Zugang, ohne Verpflichtung oder Karte. Dein Verein kann AtempoSports testen, bevor wir Bezahlpläne öffnen.",
        "multi_title": "Multisport",
        "multi_text": "Aktuell ist der Verbandssync für Rollhockey automatisch. Du kannst Fußball, Futsal, Basketball, Handball und andere Sportarten im selben Raum manuell verwalten; die automatische Verbindung mit deren Verbänden kommt bald.",
        "login_btn": "Anmelden",
        "signup_btn": "Konto erstellen — Demnächst",
    },
}


def get_landing(lang: str) -> dict[str, str]:
    """Retorna la landing en l'idioma demanat, o en català si encara no existeix."""
    return LANDING.get(lang, LANDING["ca"])
